// Datos de materias con sus atributos
const subjects = [
  // Año 1
  {
    name: "Bases biomoleculares 1",
    year: 1,
    semester: 1,
    area: "CIO",
    credits: 8,
    prerequisites: [],
  },
  {
    name: "Universidad y Profesiones de la Salud",
    year: 1,
    semester: 1,
    area: "CIO",
    credits: 3,
    prerequisites: [],
  },
  {
    name: "Salud Pública",
    year: 1,
    semester: 1,
    area: "CIO",
    credits: 12,
    prerequisites: [],
  },
  {
    name: "Aproximación a la Práctica en Terreno",
    year: 1,
    semester: 1,
    area: "CIO",
    credits: 8,
    prerequisites: [],
  },
  {
    name: "Herramientas para el Trabajo Intelectual",
    year: 1,
    semester: 1,
    area: "CIO",
    credits: 5,
    prerequisites: [],
  },
  {
    name: "Bases Histo-Anatomo Funcionales Humanas",
    year: 1,
    semester: 2,
    area: "CIO",
    credits: 12,
    prerequisites: [],
  },
  {
    name: "Introducción a la Metodología de la Investigación Científica",
    year: 1,
    semester: 2,
    area: "CIO",
    credits: 15,
    prerequisites: [],
  },
  {
    name: "Ética y Bioética",
    year: 1,
    semester: 2,
    area: "CIO",
    credits: 5,
    prerequisites: [],
  },
  {
    name: "Experiencia Práctica",
    year: 1,
    semester: 2,
    area: "CIO",
    credits: 7,
    prerequisites: [],
  },
  {
    name: "Bases Biomoleculares 2",
    year: 1,
    semester: 2,
    area: "CIO",
    credits: 12,
    prerequisites: ["Bases biomoleculares 1"],
  },
  {
    name: "Estrategias de Comunicación para el Trabajo en Equipo",
    year: 1,
    semester: 2,
    area: "CIO",
    credits: 3,
    prerequisites: [],
  },

  // Año 2
  {
    name: "UC7 - Anatomía Clínica y Bioética",
    year: 2,
    semester: 3,
    area: "Ciclo Básico Comunitario",
    credits: 34,
    prerequisites: ["CIO"],
  },
  {
    name: "UC8 - Histología y Biofísica",
    year: 2,
    semester: 3,
    area: "Ciclo Básico Comunitario",
    credits: 11,
    prerequisites: ["CIO"],
  },
  {
    name: "UC9 - Histología NCR",
    year: 2,
    semester: 4,
    area: "Ciclo Básico Comunitario",
    credits: 6,
    prerequisites: ["CIO"],
  },
  {
    name: "UC10 - Neurociencias",
    year: 2,
    semester: 4,
    area: "Ciclo Básico Comunitario",
    credits: 21,
    prerequisites: ["CIO"],
  },
  {
    name: "UC8 - Cardio y Respiratorio",
    year: 2,
    semester: 4,
    area: "Ciclo Básico Comunitario",
    credits: 18,
    prerequisites: ["CIO"],
  },

  // Año 3
  {
    name: "UC12 - DREM",
    year: 3,
    semester: 5,
    area: "Ciclo Básico Comunitario",
    credits: 45,
    prerequisites: ["UC7 - Anatomía Clínica y Bioética"],
  },
  {
    name: "UC13 - Hematología Inmunobiología",
    year: 3,
    semester: 6,
    area: "Ciclo Básico Comunitario",
    credits: 27,
    prerequisites: ["CIO"],
  },
  {
    name: "UC14 - Metodología Científica 1",
    year: 3,
    semester: 6,
    area: "Ciclo Metodología Científica 1",
    credits: 18,
    prerequisites: ["CIO"],
  },

  // Año 4
  {
    name: "UC15 - Medicina en el Primer Nivel de Atención",
    year: 4,
    semester: 0, // anual
    area: "Ciclo IntroMedicinaGeneral",
    credits: 20,
    prerequisites: [
      "Bases biomoleculares 1",
      "Universidad y Profesiones de la Salud",
      "Salud Pública",
      "Aproximación a la Práctica en Terreno",
      "Herramientas para el Trabajo Intelectual",
      "Bases Histo-Anatomo Funcionales Humanas",
      "Introducción a la Metodología de la Investigación Científica",
      "Ética y Bioética",
      "Experiencia Práctica",
      "Bases Biomoleculares 2",
      "Estrategias de Comunicación para el Trabajo en Equipo",
      "UC7 - Anatomía Clínica y Bioética",
      "UC8 - Histología y Biofísica",
      "UC9 - Histología NCR",
      "UC10 - Neurociencias",
      "UC8 - Cardio y Respiratorio",
      "UC12 - DREM",
      "UC13 - Hematología Inmunobiología",
      "UC14 - Metodología Científica 1",
    ],
  },
  {
    name: "UC16 - Bases Científicas de la Patología",
    year: 4,
    semester: 0,
    area: "Ciclo IntroMedicinaGeneral",
    credits: 35,
    prerequisites: [
      "Bases biomoleculares 1",
      "Universidad y Profesiones de la Salud",
      "Salud Pública",
      "Aproximación a la Práctica en Terreno",
      "Herramientas para el Trabajo Intelectual",
      "Bases Histo-Anatomo Funcionales Humanas",
      "Introducción a la Metodología de la Investigación Científica",
      "Ética y Bioética",
      "Experiencia Práctica",
      "Bases Biomoleculares 2",
      "Estrategias de Comunicación para el Trabajo en Equipo",
      "UC7 - Anatomía Clínica y Bioética",
      "UC8 - Histología y Biofísica",
      "UC9 - Histología NCR",
      "UC10 - Neurociencias",
      "UC8 - Cardio y Respiratorio",
      "UC12 - DREM",
      "UC13 - Hematología Inmunobiología",
      "UC14 - Metodología Científica 1",
    ],
  },
  {
    name: "UC17 - Pediatría",
    year: 4,
    semester: 0,
    area: "CicloClínicoGeneralIntegral",
    credits: 28,
    prerequisites: [
      "Bases biomoleculares 1",
      "Universidad y Profesiones de la Salud",
      "Salud Pública",
      "Aproximación a la Práctica en Terreno",
      "Herramientas para el Trabajo Intelectual",
      "Bases Histo-Anatomo Funcionales Humanas",
      "Introducción a la Metodología de la Investigación Científica",
      "Ética y Bioética",
      "Experiencia Práctica",
      "Bases Biomoleculares 2",
      "Estrategias de Comunicación para el Trabajo en Equipo",
      "UC7 - Anatomía Clínica y Bioética",
      "UC8 - Histología y Biofísica",
      "UC9 - Histología NCR",
      "UC10 - Neurociencias",
      "UC8 - Cardio y Respiratorio",
      "UC12 - DREM",
      "UC13 - Hematología Inmunobiología",
      "UC14 - Metodología Científica 1",
    ],
  },
  {
    name: "UC18 - Ginecología Y Neonatología",
    year: 4,
    semester: 0,
    area: "CicloClínicoGeneralIntegral",
    credits: 27,
    prerequisites: [
      "Bases biomoleculares 1",
      "Universidad y Profesiones de la Salud",
      "Salud Pública",
      "Aproximación a la Práctica en Terreno",
      "Herramientas para el Trabajo Intelectual",
      "Bases Histo-Anatomo Funcionales Humanas",
      "Introducción a la Metodología de la Investigación Científica",
      "Ética y Bioética",
      "Experiencia Práctica",
      "Bases Biomoleculares 2",
      "Estrategias de Comunicación para el Trabajo en Equipo",
      "UC7 - Anatomía Clínica y Bioética",
      "UC8 - Histología y Biofísica",
      "UC9 - Histología NCR",
      "UC10 - Neurociencias",
      "UC8 - Cardio y Respiratorio",
      "UC12 - DREM",
      "UC13 - Hematología Inmunobiología",
      "UC14 - Metodología Científica 1",
    ],
  },

  // Año 5
  {
    name: "UC19 - Clínica Médica",
    year: 5,
    semester: 0,
    area: "CicloClínicoGeneralIntegral",
    credits: 87,
    prerequisites: [
      "UC15 - Medicina en el Primer Nivel de Atención",
      "UC16 - Bases Científicas de la Patología",
    ],
  },
  {
    name: "UC20 - Patología Médica y Terapéutica",
    year: 5,
    semester: 0,
    area: "CicloClínicoGeneralIntegral",
    credits: 23,
    prerequisites: ["UC16 - Bases Científicas de la Patología"],
  },

  // Año 6
  {
    name: "UC21 - Clínica Quirúrgica",
    year: 6,
    semester: 0,
    area: "CicloClínicoGeneralIntegral",
    credits: 58,
    prerequisites: [
      "UC15 - Medicina en el Primer Nivel de Atención",
      "UC16 - Bases Científicas de la Patología",
    ],
  },
  {
    name: "UC22 - Patología Quirúrgica",
    year: 6,
    semester: 0,
    area: "CicloClínicoGeneralIntegral",
    credits: 11,
    prerequisites: ["UC16 - Bases Científicas de la Patología"],
  },
  {
    name: "UC23 - Medicina Familiar y Comunitaria  – Salud Mental En Comunidad – Psicología Médica",
    year: 6,
    semester: 0,
    area: "CicloClínicoGeneralIntegral",
    credits: 17,
    prerequisites: ["UC15 - Medicina en el Primer Nivel de Atención"],
  },
  {
    name: "UC24 - Metodología Científica 2",
    year: 6,
    semester: 0,
    area: "CicloMetodologíaCientífica2",
    credits: 24,
    prerequisites: [
      "UC15 - Medicina en el Primer Nivel de Atención",
      "UC16 - Bases Científicas de la Patología",
      "UC17 - Pediatría",
      "UC18 - Ginecología Y Neonatología",
      "UC19 - Clínica Médica",
      "UC21 - Clínica Quirúrgica",
      "UC23 - Medicina Familiar y Comunitaria  – Salud Mental En Comunidad – Psicología Médica",
    ],
  },

  // Año 7
  {
    name: "UC25 - Internado Rotatorio",
    year: 7,
    semester: 0,
    area: "CicloInternadoRotatorio",
    credits: 146,
    prerequisites: [
      // Todas materias previas hasta 6to año
      "Bases biomoleculares 1",
      "Universidad y Profesiones de la Salud",
      "Salud Pública",
      "Aproximación a la Práctica en Terreno",
      "Herramientas para el Trabajo